### ISSUE TITLE
[question] does it work with route caching ?

### ISSUE THREAD

**Issue by ctf0** [sebastiaanluca/laravel-router#3]
hi there, thanx that finally someone made a package to tackle the messy routing issue that been standing forever.

Jeffery Way had a similar idea since v4.2 and its kinda much easier [demo](https://ctf0.wordpress.com/2016/10/01/split-routes-into-categories-in-laravel/), however the problem i had was not being able to use route caching.

so is it possible to incorporate both of the ideas `the package & Jeffreys approach` while having the chance to use the route caching ?

**Comment by sebastiaanluca** [comment]
The idea behind both approaches is the same, I think, your example just uses regular files whereas this package provides it as classes. There's no benefit as far as I can see to put that file functionality in a package. You can do that with the 3 lines of code from the blog post.

What was the error you got when caching your routes? Since the loop will just load in the PHP files and those files contain routes (in the global namespace, outside of any classes), it should just work. It's the same as doing it in `api.php` or `web.php`.

Now you could do something like this though (pseudo code):

```php
collect(File::allFiles(__DIR__ . '/Routes'))->each(function($file) {
    Route::group($file->getPathname());
});
```

**Comment by ctf0** [comment]
thanx for the replay, so here is what i found

1-
```php
collect(File::allFiles(__DIR__ . '/Routes'))->each(function($file) {
    Route::group($file->getPathname());
});
```
wont work because `Route::group` require an array with 2 params, so to get it to work it have to be
```php
collect(File::allFiles(__DIR__ . '/Routes'))->each(function($file) {
    Route::middleware([])
        ->group($file->getPathname());
});
```

2- using the solution as in the blog post wont allow the `route:cache` to cache the files, the cmnd will work without probs but wont include those routes in cached file which is caused by the `require_once` [#7522](https://github.com/laravel/framework/issues/7522#issuecomment-75274812) , and to test i used https://www.base64decode.org/ to decode the `bootstrap/routes.php` file.

3- route closure wont work, however i was trying to find a way to make like a dummy controller that i can send the params i want to and use it like a normal function but without any luck, so i would appreciate any help with that ❤️

**Comment by antonkomarev** [comment]
If this will be cachechable - I'd like to have it in Laravel out of the box.

**Comment by sebastiaanluca** [comment]
@ctf0

1. I'm pretty sure you can omit the `middleware` method call. Middleware should be optional. Anyhow, caching will work when you use the new `group` method instead of just requiring the file like in previous Laravel versions.

3. Yeah, closures don't work with caching, but you could make a dummy controller with a `handle` method to route all requests to. Caveat there is you have to reference it for each route with `Route::get('myroute', ['uses' => 'MyController@handle']`. Since you're using controllers then, it'd be better to just use controllers all the way and use one per route (group).

@a-komarev It is, package doesn't change anything related to the core (unlike in earlier versions). All your routes get added to the router like you would do inside a `web.php` file. I plan on creating a [laravel/internals](https://github.com/laravel/internals/issues) issue to figure out if it's something Taylor would agree to.
